[nacos_cfg]
server_ip = "127.0.0.1"
server_port = 8848
app_name = "jwt-salvo-service"
app_ip = "127.0.0.1"
app_port = 3000
default_group = "DEFAULT_GROUP"
username = "admin"
password = "admin"

[client_cfg]
app_ip = "0.0.0.0"
app_port = 3000

[redis_cfg]
uri = "redis://127.0.0.1:6379/"
max_size = 50
min_idle = 10
max_lifetime = 60
idle_timeout = 60
connection_timeout = 5
test_on_check_out = true
