[nacos_cfg]
server_ip = "127.0.0.1"
server_port = 8848
service_name = "jwt-salvo-service"
service_ip = "127.0.0.1"
service_port = 3000
weight = 1.5
group_name = "DEFAULT_GROUP"
namespace = ""
cluster_name = "DEFAULT"
username = "admin"
password = "admin"

[client_cfg]
service_ip = "0.0.0.0"
service_port = 3000

[redis_cfg]
uri = "redis://127.0.0.1:6379/"
max_size = 50
min_idle = 10
max_lifetime = 60
idle_timeout = 60
connection_timeout = 5
test_on_check_out = true
